movies = [
    "3 Idiots",
    "Lagaan",
    "Dilwale Dulhania Le Jayenge",
    "Sholay",
    "Kabhi Khushi Kabhie Gham",
    "Dangal",
    "PK",
    "Bajrangi Bhaijaan",
    "Baahubali: The Beginning",
    "Baahubali: The Conclusion",
    "Gully Boy",
    "Zindagi Na Milegi Dobara",
    "Dil Chahta Hai",
    "Kuch Kuch Hota Hai",
    "My Name is Khan",
    "Chak De! India",
    "Bajirao Mastani",
    "Padmaavat",
    "Barfi!",
    "Queen",
    "Taare Zameen Par",
    "Rang De Basanti",
    "Andhadhun",
    "Stree",
    "Tumbbad",
    "Article 15",
    "Haider",
    "Gangs of Wasseypur",
    "Paan Singh Tomar",
    "Drishyam",
    "Kahaani",
    "Badhaai Ho",
    "Newton",
    "Piku",
    "Uri: The Surgical Strike",
    "Sanju",
    "Raazi",
    "Dhoom",
    "Dhoom 2",
    "Dhoom 3",
    "Don",
    "Don 2",
    "Mughal-e-Azam",
    "Mother India",
    "Pyaasa",
    "Deewaar",
    "Amar Akbar Anthony",
    "Satyam Shivam Sundaram",
    "Karz",
    "Mr. India",
    "Dil Se",
    "Hum Aapke Hain Koun..!",
    "Maine Pyar Kiya",
    "Hum Dil De Chuke Sanam",
    "Kal Ho Naa Ho",
    "Kabhi Alvida Naa Kehna",
    "Veer-Zaara",
    "Jab Tak Hai Jaan",
    "Rab Ne Bana Di Jodi",
    "Sultan",
    "Ek Tha Tiger",
    "Tiger Zinda Hai",
    "Race",
    "Race 2",
    "Race 3",
    "Krrish",
    "Krrish 3",
    "Koi... Mil Gaya",
    "Shree 420",
    "Awara",
    "Guide",
    "Aradhana",
    "Amar Prem",
    "Anand",
    "Gol Maal",
    "Chupke Chupke",
    "Chhoti Si Baat",
    "Jaane Bhi Do Yaaro",
    "Dilwale",
    "Singham",
    "Singham Returns",
    "Simba",
    "Golmaal: Fun Unlimited",
    "Golmaal Returns",
    "Golmaal 3",
    "Golmaal Again",
    "Om Shanti Om",
    "Chennai Express",
    "Jab Harry Met Sejal",
    "Raees",
    "Fan",
    "Happy New Year",
    "Main Hoon Na",
    "Kabir Singh",
    "Simmba",
    "Brahmastra",
    "War",
    "Bang Bang!",
    "The Shawshank Redemption",
    "The Godfather",
    "The Dark Knight",
    "Pulp Fiction",
    "Forrest Gump",
    "Inception",
    "Fight Club",
    "The Matrix",
    "The Lord of the Rings: The Return of the King",
    "Star Wars: Episode IV - A New Hope",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Two Towers",
    "Star Wars: Episode V - The Empire Strikes Back",
    "The Silence of the Lambs",
    "Schindler's List",
    "Saving Private Ryan",
    "The Green Mile",
    "Interstellar",
    "Gladiator",
    "Jurassic Park",
    "Titanic",
    "The Avengers",
    "Avengers: Endgame",
    "Avengers: Infinity War",
    "Iron Man",
    "Iron Man 2",
    "Iron Man 3",
    "Captain America: The First Avenger",
    "Captain America: The Winter Soldier",
    "Captain America: Civil War",
    "Guardians of the Galaxy",
    "Guardians of the Galaxy Vol. 2",
    "Black Panther",
    "Thor",
    "Thor: The Dark World",
    "Thor: Ragnarok",
    "Spider-Man: Homecoming",
    "Spider-Man: Far From Home",
    "Doctor Strange",
    "Ant-Man",
    "Ant-Man and the Wasp",
    "Deadpool",
    "Deadpool 2",
    "Logan",
    "X-Men",
    "X2",
    "X-Men: The Last Stand",
    "X-Men: First Class",
    "X-Men: Days of Future Past",
    "X-Men: Apocalypse",
    "X-Men: Dark Phoenix",
    "Batman Begins",
    "The Dark Knight Rises",
    "Man of Steel",
    "Wonder Woman",
    "Aquaman",
    "Justice League",
    "Suicide Squad",
    "Joker",
    "The Lion King",
    "Beauty and the Beast",
    "Aladdin",
    "Frozen",
    "Frozen II",
    "Toy Story",
    "Toy Story 2",
    "Toy Story 3",
    "Toy Story 4",
    "Finding Nemo",
    "Finding Dory",
    "The Incredibles",
    "The Incredibles 2",
    "Monsters, Inc.",
    "Monsters University",
    "Cars",
    "Cars 2",
    "Cars 3",
    "Up",
    "Ratatouille",
    "Brave",
    "Coco",
    "Inside Out",
    "WALL-E",
    "A Bug's Life",
    "Zootopia",
    "Moana",
    "Tangled",
    "The Little Mermaid",
    "Mulan",
    "Pocahontas",
    "Hercules",
    "Tarzan",
    "Lilo & Stitch",
    "The Princess and the Frog",
    "Big Hero 6",
    "Wreck-It Ralph",
    "Ralph Breaks the Internet",
    "The Jungle Book",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Pirates of the Caribbean: Dead Man's Chest",
    "Pirates of the Caribbean: At World's End",
    "Pirates of the Caribbean: On Stranger Tides",
    "Pirates of the Caribbean: Dead Men Tell No Tales"
]


bollywood_movies = [
    "3 Idiots",
    "Lagaan",
    "Dilwale Dulhania Le Jayenge",
    "Sholay",
    "Kabhi Khushi Kabhie Gham",
    "Dangal",
    "PK",
    "Bajrangi Bhaijaan",
    "Baahubali: The Beginning",
    "Baahubali: The Conclusion",
    "Gully Boy",
    "Zindagi Na Milegi Dobara",
    "Dil Chahta Hai",
    "Kuch Kuch Hota Hai",
    "My Name is Khan",
    "Chak De! India",
    "Bajirao Mastani",
    "Padmaavat",
    "Barfi!",
    "Queen",
    "Taare Zameen Par",
    "Rang De Basanti",
    "Andhadhun",
    "Stree",
    "Tumbbad",
    "Article 15",
    "Haider",
    "Gangs of Wasseypur",
    "Paan Singh Tomar",
    "Drishyam",
    "Kahaani",
    "Badhaai Ho",
    "Newton",
    "Piku",
    "Uri: The Surgical Strike",
    "Sanju",
    "Raazi",
    "Dhoom",
    "Dhoom 2",
    "Dhoom 3",
    "Don",
    "Don 2",
    "Mughal-e-Azam",
    "Mother India",
    "Pyaasa",
    "Deewaar",
    "Amar Akbar Anthony",
    "Satyam Shivam Sundaram",
    "Karz",
    "Mr. India",
    "Dil Se",
    "Hum Aapke Hain Koun..!",
    "Maine Pyar Kiya",
    "Hum Dil De Chuke Sanam",
    "Kal Ho Naa Ho",
    "Kabhi Alvida Naa Kehna",
    "Veer-Zaara",
    "Jab Tak Hai Jaan",
    "Rab Ne Bana Di Jodi",
    "Sultan",
    "Ek Tha Tiger",
    "Tiger Zinda Hai",
    "Race",
    "Race 2",
    "Race 3",
    "Krrish",
    "Krrish 3",
    "Koi... Mil Gaya",
    "Don",
    "Shree 420",
    "Awara",
    "Guide",
    "Aradhana",
    "Amar Prem",
    "Anand",
    "Gol Maal",
    "Chupke Chupke",
    "Chhoti Si Baat",
    "Jaane Bhi Do Yaaro",
    "Dilwale",
    "Singham",
    "Singham Returns",
    "Simba",
    "Golmaal: Fun Unlimited",
    "Golmaal Returns",
    "Golmaal 3",
    "Golmaal Again",
    "Om Shanti Om",
    "Chennai Express",
    "Jab Harry Met Sejal",
    "Raees",
    "Fan",
    "Happy New Year",
    "Main Hoon Na",
    "Kabir Singh",
    "Simmba",
    "Brahmastra",
    "War",
    "Bang Bang!"
]
hollywood_movies = [
    "The Shawshank Redemption",
    "The Godfather",
    "The Dark Knight",
    "Pulp Fiction",
    "Forrest Gump",
    "Inception",
    "Fight Club",
    "The Matrix",
    "The Lord of the Rings: The Return of the King",
    "Star Wars: Episode IV - A New Hope",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Two Towers",
    "Star Wars: Episode V - The Empire Strikes Back",
    "The Silence of the Lambs",
    "Schindler's List",
    "Saving Private Ryan",
    "The Green Mile",
    "Interstellar",
    "Gladiator",
    "Jurassic Park",
    "Titanic",
    "The Avengers",
    "Avengers: Endgame",
    "Avengers: Infinity War",
    "Iron Man",
    "Iron Man 2",
    "Iron Man 3",
    "Captain America: The First Avenger",
    "Captain America: The Winter Soldier",
    "Captain America: Civil War",
    "Guardians of the Galaxy",
    "Guardians of the Galaxy Vol. 2",
    "Black Panther",
    "Thor",
    "Thor: The Dark World",
    "Thor: Ragnarok",
    "Spider-Man: Homecoming",
    "Spider-Man: Far From Home",
    "Doctor Strange",
    "Ant-Man",
    "Ant-Man and the Wasp",
    "Deadpool",
    "Deadpool 2",
    "Logan",
    "X-Men",
    "X2",
    "X-Men: The Last Stand",
    "X-Men: First Class",
    "X-Men: Days of Future Past",
    "X-Men: Apocalypse",
    "X-Men: Dark Phoenix",
    "Batman Begins",
    "The Dark Knight Rises",
    "Man of Steel",
    "Wonder Woman",
    "Aquaman",
    "Justice League",
    "Suicide Squad",
    "Joker",
    "The Lion King",
    "Beauty and the Beast",
    "Aladdin",
    "Frozen",
    "Frozen II",
    "Toy Story",
    "Toy Story 2",
    "Toy Story 3",
    "Toy Story 4",
    "Finding Nemo",
    "Finding Dory",
    "The Incredibles",
    "The Incredibles 2",
    "Monsters, Inc.",
    "Monsters University",
    "Cars",
    "Cars 2",
    "Cars 3",
    "Up",
    "Ratatouille",
    "Brave",
    "Coco",
    "Inside Out",
    "WALL-E",
    "A Bug's Life",
    "Zootopia",
    "Moana",
    "Tangled",
    "The Little Mermaid",
    "Mulan",
    "Pocahontas",
    "Hercules",
    "Tarzan",
    "Lilo & Stitch",
    "The Princess and the Frog",
    "Big Hero 6",
    "Wreck-It Ralph",
    "Ralph Breaks the Internet",
    "The Jungle Book",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Pirates of the Caribbean: Dead Man's Chest",
    "Pirates of the Caribbean: At World's End",
    "Pirates of the Caribbean: On Stranger Tides",
    "Pirates of the Caribbean: Dead Men Tell No Tales"
]

